version: '3'
services:
  reverse-proxy:
    image: traefik
    command: --api.insecure=true --providers.docker --providers.docker.exposedByDefault=false
    restart: "no"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
     depends_on:
     - hexToRgb
     - hslToHex

  hexToRgb:
    image: hexToRgb
    restart: "no"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.hexToRgb.rule=PathPrefix(`/hexToRgb`)"
      - "traefik.http.routers.hexToRgb.middlewares=hexToRgb-stripprefix"
      - "traefik.http.middlewares.hexToRgb.stripprefix.prefixes=/hexToRgb"

  hslToRgb:
    image: hslToHex
    restart: "no"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.HslToHex.rule=PathPrefix(`/hslToRgb`)"
      - "traefik.http.routers.hslToRgb.middlewares=hslToRgb-stripprefix"
      - "traefik.http.middlewares.hslToRgb-stripprefix.stripprefix.prefixes=/hslToRgb"
