version: '3'
services:
  reverse-proxy:
    image: traefik
    command: --api.insecure=true --providers.docker --providers.docker.exposedByDefault=false
    restart: "no"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - hex_to_rgb
      - hsl_to_hex

  hex_to_rgb:
    image: hex_to_rgb
    restart: "no"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.hex_to_rgb.rule=PathPrefix(`/hex_to_rgb`)"
      - "traefik.http.routers.hex_to_rgb.middlewares=hex_to_rgb-stripprefix"
      - "traefik.http.middlewares.hex_to_rgb.stripprefix.prefixes=/hex_to_rgb"

  hsl_to_hex:
    image: hsl_to_hex
    restart: "no"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.hsl_to_hex.rule=PathPrefix(`/hsl_to_hex`)"
      - "traefik.http.routers.hsl_to_hex.middlewares=hsl_to_hex-stripprefix"
      - "traefik.http.middlewares.hsl_to_hex-stripprefix.stripprefix.prefixes=/hsl_to_hex"
